name: CI/CD to Heroku

on:
  push:
    branches: [ develop ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      shell: bash
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: $REPOSITORY_NAME #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true

    #- name: Test
    #  run: go test -v ./...